In [7]:
# Load libraries

import pandas as pd 
import numpy as np

In [8]:
df = pd.read_csv("/Users/sahilsoni/Desktop/DA/Projects/market_data_clean.csv")

In [9]:
df.shape

(742, 42)

In [10]:
df.head()

,ID,Job_Title,Salary_Estimate,FIELD4,Rating,Company_Name,Location,Headquarters,Size,Founded,...,tensor,hadoop,tableau,bi,flink,mongo,google_an,job_title_sim,seniority_by_title,Degree
0,0,Data Scientist,$53K-$91K (Glassdoor est.),NaN,3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 - 1000,1973,...,0,0,1,1,0,0,0,data scientist,na,M
1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),NaN,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+,1984,...,0,0,0,0,0,0,0,data scientist,na,M
2,2,Data Scientist,$80K-$90K (Glassdoor est.),NaN,4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 - 1000,2010,...,0,0,0,0,0,0,0,data scientist,na,M
3,3,Data Scientist,$56K-$97K (Glassdoor est.),NaN,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 - 5000,1965,...,0,0,0,0,0,0,0,data scientist,na,na
4,4,Data Scientist,$86K-$143K (Glassdoor est.),NaN,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 - 200,1998,...,0,0,0,0,0,0,0,data scientist,na,na

In [11]:
df.columns

Index(['ID', 'Job_Title', 'Salary_Estimate', 'FIELD4', 'Rating',
       'Company_Name', 'Location', 'Headquarters', 'Size', 'Founded',
       'Type_of_ownership', 'Industry', 'Sector', 'Revenue', 'Competitors',
       'Hourly', 'Employer_provided', 'Lower_Salary', 'Upper_Salary',
       'Avg_SalaryK', 'company_txt', 'Job_Location', 'Age', 'Python', 'spark',
       'aws', 'excel', 'sql_', 'sas', 'keras', 'pytorch', 'scikit', 'tensor',
       'hadoop', 'tableau', 'bi', 'flink', 'mongo', 'google_an',
       'job_title_sim', 'seniority_by_title', 'Degree'],
      dtype='object')

In [12]:
df.isnull().sum()

ID                      0
Job_Title               0
Salary_Estimate         0
FIELD4                742
Rating                  0
Company_Name            0
Location                0
Headquarters            0
Size                    0
Founded                 0
Type_of_ownership       0
Industry                0
Sector                  0
Revenue                 0
Competitors             0
Hourly                  0
Employer_provided       0
Lower_Salary            0
Upper_Salary            0
Avg_SalaryK             0
company_txt             0
Job_Location            0
Age                     0
Python                  0
spark                   0
aws                     0
excel                   0
sql_                    0
sas                     0
keras                   0
pytorch                 0
scikit                  0
tensor                  0
hadoop                  0
tableau                 0
bi                      0
flink                   0
mongo                   0
google_an               0
job_title_sim           0
seniority_by_title      0
Degree                  0
dtype: int64

In [13]:
(df == -1).sum()

ID                     0
Job_Title              0
Salary_Estimate        0
FIELD4                 0
Rating                11
Company_Name           0
Location               0
Headquarters           0
Size                   0
Founded               50
Type_of_ownership      0
Industry               0
Sector                 0
Revenue                0
Competitors            0
Hourly                 0
Employer_provided      0
Lower_Salary           0
Upper_Salary           0
Avg_SalaryK            0
company_txt            0
Job_Location           0
Age                   50
Python                 0
spark                  0
aws                    0
excel                  0
sql_                   0
sas                    0
keras                  0
pytorch                0
scikit                 0
tensor                 0
hadoop                 0
tableau                0
bi                     0
flink                  0
mongo                  0
google_an              0
job_title_sim          0
seniority_by_title     0
Degree                 0
dtype: int64

In [14]:
df.describe()

,ID,FIELD4,Rating,Founded,Hourly,Employer_provided,Lower_Salary,Upper_Salary,Avg_SalaryK,Age,...,keras,pytorch,scikit,tensor,hadoop,tableau,bi,flink,mongo,google_an
count,742.000000,0.0,742.000000,742.000000,742.000000,742.000000,742.000000,742.000000,742.000000,742.000000,...,742.000000,742.000000,742.000000,742.000000,742.000000,742.000000,742.000000,742.000000,742.000000,742.000000
mean,370.500000,NaN,3.618868,1837.154987,0.032345,0.022911,74.754717,128.214286,101.484501,47.524259,...,0.039084,0.052561,0.072776,0.097035,0.167116,0.199461,0.075472,0.013477,0.049865,0.018868
std,214.341239,NaN,0.801210,497.183763,0.177034,0.149721,30.945892,45.128650,37.482449,53.839080,...,0.193925,0.223305,0.259944,0.296205,0.373331,0.399865,0.264329,0.115384,0.217813,0.136150
min,0.000000,NaN,-1.000000,-1.000000,0.000000,0.000000,15.000000,16.000000,15.500000,-1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,185.250000,NaN,3.300000,1939.000000,0.000000,0.000000,52.000000,96.000000,73.500000,12.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,370.500000,NaN,3.700000,1988.000000,0.000000,0.000000,69.500000,124.000000,97.500000,25.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,555.750000,NaN,4.000000,2007.000000,0.000000,0.000000,91.000000,155.000000,122.500000,60.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,741.000000,NaN,5.000000,2019.000000,1.000000,1.000000,202.000000,306.000000,254.000000,277.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [15]:
df.drop(columns=['FIELD4'], inplace = True)

In [16]:
df['Company_Name'] = df['Company_Name'].str.split('\n').str[0]

In [17]:
df.head()

,ID,Job_Title,Salary_Estimate,Rating,Company_Name,Location,Headquarters,Size,Founded,Type_of_ownership,...,tensor,hadoop,tableau,bi,flink,mongo,google_an,job_title_sim,seniority_by_title,Degree
0,0,Data Scientist,$53K-$91K (Glassdoor est.),3.8,Tecolote Research,"Albuquerque, NM","Goleta, CA",501 - 1000,1973,Company - Private,...,0,0,1,1,0,0,0,data scientist,na,M
1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),3.4,University of Maryland Medical System,"Linthicum, MD","Baltimore, MD",10000+,1984,Other Organization,...,0,0,0,0,0,0,0,data scientist,na,M
2,2,Data Scientist,$80K-$90K (Glassdoor est.),4.8,KnowBe4,"Clearwater, FL","Clearwater, FL",501 - 1000,2010,Company - Private,...,0,0,0,0,0,0,0,data scientist,na,M
3,3,Data Scientist,$56K-$97K (Glassdoor est.),3.8,PNNL,"Richland, WA","Richland, WA",1001 - 5000,1965,Government,...,0,0,0,0,0,0,0,data scientist,na,na
4,4,Data Scientist,$86K-$143K (Glassdoor est.),2.9,Affinity Solutions,"New York, NY","New York, NY",51 - 200,1998,Company - Private,...,0,0,0,0,0,0,0,data scientist,na,na

In [18]:
df['Salary_Estimate'] = df['Salary_Estimate'].str.replace(r'\(.*\)', '', regex=True).str.strip()

In [19]:
df.head()

,ID,Job_Title,Salary_Estimate,Rating,Company_Name,Location,Headquarters,Size,Founded,Type_of_ownership,...,tensor,hadoop,tableau,bi,flink,mongo,google_an,job_title_sim,seniority_by_title,Degree
0,0,Data Scientist,$53K-$91K,3.8,Tecolote Research,"Albuquerque, NM","Goleta, CA",501 - 1000,1973,Company - Private,...,0,0,1,1,0,0,0,data scientist,na,M
1,1,Healthcare Data Scientist,$63K-$112K,3.4,University of Maryland Medical System,"Linthicum, MD","Baltimore, MD",10000+,1984,Other Organization,...,0,0,0,0,0,0,0,data scientist,na,M
2,2,Data Scientist,$80K-$90K,4.8,KnowBe4,"Clearwater, FL","Clearwater, FL",501 - 1000,2010,Company - Private,...,0,0,0,0,0,0,0,data scientist,na,M
3,3,Data Scientist,$56K-$97K,3.8,PNNL,"Richland, WA","Richland, WA",1001 - 5000,1965,Government,...,0,0,0,0,0,0,0,data scientist,na,na
4,4,Data Scientist,$86K-$143K,2.9,Affinity Solutions,"New York, NY","New York, NY",51 - 200,1998,Company - Private,...,0,0,0,0,0,0,0,data scientist,na,na

In [20]:
df.replace(-1, pd.NA, inplace=True)

In [21]:
df.head()

,ID,Job_Title,Salary_Estimate,Rating,Company_Name,Location,Headquarters,Size,Founded,Type_of_ownership,...,tensor,hadoop,tableau,bi,flink,mongo,google_an,job_title_sim,seniority_by_title,Degree
0,0,Data Scientist,$53K-$91K,3.8,Tecolote Research,"Albuquerque, NM","Goleta, CA",501 - 1000,1973,Company - Private,...,0,0,1,1,0,0,0,data scientist,na,M
1,1,Healthcare Data Scientist,$63K-$112K,3.4,University of Maryland Medical System,"Linthicum, MD","Baltimore, MD",10000+,1984,Other Organization,...,0,0,0,0,0,0,0,data scientist,na,M
2,2,Data Scientist,$80K-$90K,4.8,KnowBe4,"Clearwater, FL","Clearwater, FL",501 - 1000,2010,Company - Private,...,0,0,0,0,0,0,0,data scientist,na,M
3,3,Data Scientist,$56K-$97K,3.8,PNNL,"Richland, WA","Richland, WA",1001 - 5000,1965,Government,...,0,0,0,0,0,0,0,data scientist,na,na
4,4,Data Scientist,$86K-$143K,2.9,Affinity Solutions,"New York, NY","New York, NY",51 - 200,1998,Company - Private,...,0,0,0,0,0,0,0,data scientist,na,na

In [22]:
df['Rating'] = df['Rating'].fillna(df['Rating'].mean())

/var/folders/g5/6y7fl74s4k18sq82p57137cw0000gn/T/ipykernel_11547/925589756.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Rating'] = df['Rating'].fillna(df['Rating'].mean())

In [23]:
df['Rating']

0      3.8
1      3.4
2      4.8
3      3.8
4      2.9
      ...
737    3.9
738    4.4
739    2.6
740    3.2
741    3.6
Name: Rating, Length: 742, dtype: float64

In [24]:
df['Founded'] = df['Founded'].fillna(df['Founded'].median())    # median is better than mean for years

df['Age'] = df['Age'].fillna(df['Age'].median())            # same for age

/var/folders/g5/6y7fl74s4k18sq82p57137cw0000gn/T/ipykernel_11547/3031065338.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Founded'] = df['Founded'].fillna(df['Founded'].median())    # median is better than mean for years
/var/folders/g5/6y7fl74s4k18sq82p57137cw0000gn/T/ipykernel_11547/3031065338.py:3: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Age'] = df['Age'].fillna(df['Age'].median())            # same for age

In [25]:
df['Founded']

0      1973.0
1      1984.0
2      2010.0
3      1965.0
4      1998.0
        ...
737    1830.0
738    2006.0
739    1984.0
740    1992.0
741    1967.0
Name: Founded, Length: 742, dtype: float64

In [26]:
df['Age']

0       48.0
1       37.0
2       11.0
3       56.0
4       23.0
       ...
737    191.0
738     15.0
739     37.0
740     29.0
741     54.0
Name: Age, Length: 742, dtype: float64

In [27]:
df['Lower_Salary'] = df['Lower_Salary'].fillna(df['Lower_Salary'].median())

df['Upper_Salary'] = df['Upper_Salary'].fillna(df['Upper_Salary'].median())

df['Avg_SalaryK'] = df['Avg_SalaryK'].fillna(df['Avg_SalaryK'].median())

In [28]:
df['Lower_Salary']

0      53
1      63
2      80
3      56
4      86
       ..
737    58
738    72
739    56
740    95
741    61
Name: Lower_Salary, Length: 742, dtype: int64

In [29]:
df['Upper_Salary']

0       91
1      112
2       90
3       97
4      143
      ...
737    111
738    133
739     91
740    160
741    126
Name: Upper_Salary, Length: 742, dtype: int64

In [30]:
df['Avg_SalaryK']

0       72.0
1       87.5
2       85.0
3       76.5
4      114.5
       ...
737     84.5
738    102.5
739     73.5
740    127.5
741     93.5
Name: Avg_SalaryK, Length: 742, dtype: float64

In [31]:
text_cols = ['Size', 'Industry', 'Sector', 'Revenue', 'Competitors', 'Headquarters', 'Type_of_ownership']

df[text_cols] = df[text_cols].fillna('Unknown')    # fill all text NaN with 'Unknown' in one line

In [32]:
df.head()

,ID,Job_Title,Salary_Estimate,Rating,Company_Name,Location,Headquarters,Size,Founded,Type_of_ownership,...,tensor,hadoop,tableau,bi,flink,mongo,google_an,job_title_sim,seniority_by_title,Degree
0,0,Data Scientist,$53K-$91K,3.8,Tecolote Research,"Albuquerque, NM","Goleta, CA",501 - 1000,1973.0,Company - Private,...,0,0,1,1,0,0,0,data scientist,na,M
1,1,Healthcare Data Scientist,$63K-$112K,3.4,University of Maryland Medical System,"Linthicum, MD","Baltimore, MD",10000+,1984.0,Other Organization,...,0,0,0,0,0,0,0,data scientist,na,M
2,2,Data Scientist,$80K-$90K,4.8,KnowBe4,"Clearwater, FL","Clearwater, FL",501 - 1000,2010.0,Company - Private,...,0,0,0,0,0,0,0,data scientist,na,M
3,3,Data Scientist,$56K-$97K,3.8,PNNL,"Richland, WA","Richland, WA",1001 - 5000,1965.0,Government,...,0,0,0,0,0,0,0,data scientist,na,na
4,4,Data Scientist,$86K-$143K,2.9,Affinity Solutions,"New York, NY","New York, NY",51 - 200,1998.0,Company - Private,...,0,0,0,0,0,0,0,data scientist,na,na

In [33]:
df['State'] = df['Location'].str.split(',').str[-1].str.strip()    # "New York, NY" → "NY"

In [34]:
df['State']

0      NM
1      MD
2      FL
3      WA
4      NY
       ..
737    MA
738    TN
739    PA
740    PA
741    OH
Name: State, Length: 742, dtype: object

In [35]:
df.head()

,ID,Job_Title,Salary_Estimate,Rating,Company_Name,Location,Headquarters,Size,Founded,Type_of_ownership,...,hadoop,tableau,bi,flink,mongo,google_an,job_title_sim,seniority_by_title,Degree,State
0,0,Data Scientist,$53K-$91K,3.8,Tecolote Research,"Albuquerque, NM","Goleta, CA",501 - 1000,1973.0,Company - Private,...,0,1,1,0,0,0,data scientist,na,M,NM
1,1,Healthcare Data Scientist,$63K-$112K,3.4,University of Maryland Medical System,"Linthicum, MD","Baltimore, MD",10000+,1984.0,Other Organization,...,0,0,0,0,0,0,data scientist,na,M,MD
2,2,Data Scientist,$80K-$90K,4.8,KnowBe4,"Clearwater, FL","Clearwater, FL",501 - 1000,2010.0,Company - Private,...,0,0,0,0,0,0,data scientist,na,M,FL
3,3,Data Scientist,$56K-$97K,3.8,PNNL,"Richland, WA","Richland, WA",1001 - 5000,1965.0,Government,...,0,0,0,0,0,0,data scientist,na,na,WA
4,4,Data Scientist,$86K-$143K,2.9,Affinity Solutions,"New York, NY","New York, NY",51 - 200,1998.0,Company - Private,...,0,0,0,0,0,0,data scientist,na,na,NY

In [36]:
skill_cols = ['Python', 'spark', 'aws', 'excel', 'sql_', 'tableau', 'bi', 'hadoop', 'tensor', 'flink', 'mongo', 'google_an']

df[skill_cols] = df[skill_cols].fillna(0)    # missing skill means not required = 0

In [37]:
df[skill_cols]

,Python,spark,aws,excel,sql_,tableau,bi,hadoop,tensor,flink,mongo,google_an
0,1,0,0,1,0,1,1,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,0,0
2,1,1,0,1,1,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,0,0
4,1,0,0,1,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
737,0,0,1,0,0,0,0,0,0,0,0,0
738,1,1,1,0,1,0,0,1,0,0,0,0
739,0,0,0,1,0,0,0,0,0,0,0,0
740,0,0,0,1,0,0,0,0,0,0,0,0
741,1,0,0,0,0,0,0,0,0,0,0,0

In [38]:
df.isnull().sum()    # should show 0 or very low missing values now

df.shape             # should still be 742 rows

df.head()            # visual check

,ID,Job_Title,Salary_Estimate,Rating,Company_Name,Location,Headquarters,Size,Founded,Type_of_ownership,...,hadoop,tableau,bi,flink,mongo,google_an,job_title_sim,seniority_by_title,Degree,State
0,0,Data Scientist,$53K-$91K,3.8,Tecolote Research,"Albuquerque, NM","Goleta, CA",501 - 1000,1973.0,Company - Private,...,0,1,1,0,0,0,data scientist,na,M,NM
1,1,Healthcare Data Scientist,$63K-$112K,3.4,University of Maryland Medical System,"Linthicum, MD","Baltimore, MD",10000+,1984.0,Other Organization,...,0,0,0,0,0,0,data scientist,na,M,MD
2,2,Data Scientist,$80K-$90K,4.8,KnowBe4,"Clearwater, FL","Clearwater, FL",501 - 1000,2010.0,Company - Private,...,0,0,0,0,0,0,data scientist,na,M,FL
3,3,Data Scientist,$56K-$97K,3.8,PNNL,"Richland, WA","Richland, WA",1001 - 5000,1965.0,Government,...,0,0,0,0,0,0,data scientist,na,na,WA
4,4,Data Scientist,$86K-$143K,2.9,Affinity Solutions,"New York, NY","New York, NY",51 - 200,1998.0,Company - Private,...,0,0,0,0,0,0,data scientist,na,na,NY

In [39]:
type(df)    # should say <class 'pandas.core.frame.DataFrame'>

pandas.core.frame.DataFrame

In [40]:
df.reset_index()    # reset index to clean 0,1,2,3...

df['ID'] = df.index    # assign clean sequential ID to ID column

df['ID'].head()    # verify

0    0
1    1
2    2
3    3
4    4
Name: ID, dtype: int64

In [41]:
df['Competitors'] = df['Competitors'].replace('-1', 'Unknown')    # replace text -1 with Unknown

In [42]:
df['Competitors']

0                                                Unknown
1                                                Unknown
2                                                Unknown
3      Oak Ridge National Laboratory, National Renewa...
4                   Commerce Signals, Cardlytics, Yodlee
                             ...
737                           Pfizer, AstraZeneca, Merck
738                      See Tickets, TicketWeb, Vendini
739                                              Unknown
740                                              Unknown
741                                              Unknown
Name: Competitors, Length: 742, dtype: object

In [43]:
df['Founded'] = df['Founded'].astype(int)    # convert 1973.0 → 1973

In [44]:
df['Founded']

0      1973
1      1984
2      2010
3      1965
4      1998
       ...
737    1830
738    2006
739    1984
740    1992
741    1967
Name: Founded, Length: 742, dtype: int64

In [45]:
df.to_csv("market_data_clean.csv", index=False)    # overwrite with fully clean file

print("Done!", df.shape)

Done! (742, 42)